---
- name: Execute Shell Commands
  hosts: all
  gather_facts: false

  vars:
    the_command: "kubectl get pods"

  tasks:
    - name: Run a single shell command
      ansible.builtin.shell: "{{ the_command }}"
      register: response

    - name: Print the output of the previous command
      ansible.builtin.debug:
        msg: " {{ response.stdout }}"